pages_about:
    resource: "@PagesAboutBundle/Resources/config/routing.yml"
    prefix:   /

mis_med_media:
    resource: "@MisMedMediaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
