<?php

namespace MisMed\MediaBundle\Repository;

/**
 * PortfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfRepository extends \Doctrine\ORM\EntityRepository
{
}
