<?php

namespace MisMed\MediaBundle\Repository;

/**
 * PortfolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolRepository extends \Doctrine\ORM\EntityRepository
{
}
