<?php

namespace MisMed\MediaBundle\Repository;

/**
 * ØüïRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ØüïRepository extends \Doctrine\ORM\EntityRepository
{
}
